SYSTEM:
  NUM_CPUS: 8
  NUM_GPUS: 0
DATASET:
  EM_PATH: 'datasets/human/human_em_export_8nm/'
  LABEL_PATH: 'datasets/human/human_gt_export_8nm/'
  FILE_FORMAT: 'png'
  CHUNK_SIZE: [2, 4096, 4096]
  ROOTF: 'features/human/'
  ROOTD: 'datasets/human/'
  DATAINFO: 'features/human/data_info.json'
PTC:
  ARCHITECTURE: 'pnae'
  LATENT_SPACE: 100
  BATCH_SIZE: 16
  EPOCHS: 100
  INPUT_DATA: 'datasets/human/pts.h5'
  SAMPLE_SIZE: 20000
  SAMPLE_MODE: 'montecarlo'
  INPUT_DATA_SAMPLED: 'datasets/human/mc_pts.h5'
  MONITOR_PATH: 'models/ptc/human/'
  FEATURE_NAME: 'human/ptc_shapef'
  MODEL: 'models/ptc/human/run_2021-10-11/vae_ptc_model_15.pt'
MODE:
  PROCESS: 'ptcinfer'
CLUSTER:
  ALG: 'kmeans'
  FEAT_LIST: ['sizef', 'distf', 'circf', 'shapef', 'texturef']
  WEIGHTSF: [1, 1, 1, 1, 1]
  N_CLUSTER: 5
  OUTPUTPATH: 'outputs/human/'
