SYSTEM:
  NUM_CPUS: 8
  NUM_GPUS: 0
AUTOENCODER:
  ARCHITECTURE: 'unet_3d'
  REGION_LIMIT: None
  CHUNKS_CPU: 4
  UPPER_BOUND: 10000000
  LOWER_BOUND: 0
  TARGET: (64, 64, 64)
  EPOCHS: 5
  BATCH_SIZE: 1
  OUTPUT_FOLDER: 'features/mouseA/'
  FEATURES: ['shape', 'texture']
  LATENT_SPACE: 100
  MAX_MEAN: 0.001
  MAX_VAR: 0.001
  MAX_GRADIENT: 1.0
  LOG_INTERVAL: 10
  LARGE_OBJECT_SAMPLES: 10
PTC:
  BATCH_SIZE: 1
  EPOCHS: 25
  INPUT_DATA: 'datasets/mouseA/pts.h5'
  MONITOR_PATH: 'models/ptc/mouseA/'
  FEATURE_NAME: 'mouseA/ptc_shapef'
DATASET:
  EM_PATH: 'datasets/mouseA/em_export/'
  LABEL_PATH: 'datasets/mouseA/mito_export_unique_id/'
  GT_PATH: 'datasets/mouseA/mito_export_allgroups/'
  ROOTF: 'features/mouseA/'
  ROOTD: 'datasets/mouseA/'
  DATAINFO: 'features/mouseA/data_info.json'
MODE:
  PROCESS: 'ptctrain'
CLUSTER:
  ALG: 'kmeans'
  FEAT_LIST: ['sizef', 'distf', 'circf', 'shapef', 'texturef']
  WEIGHTSF: [1, 1, 1, 1, 1]
  N_CLUSTER: 5
  OUTPUTPATH: 'outputs/mouseA/'
  GENERATE_MASKS: True
