SYSTEM:
  NUM_CPUS: 4
  NUM_GPUS: 0
DATASET:
  EM_PATH: 'datasets/mouseA/em_export/'
  LABEL_PATH: 'datasets/mouseA/mito_export_unique_id/'
  GT_PATH: 'datasets/mouseA/mito_export_maingroups/'
  ROOTF: 'features/mouseA/'
  ROOTD: 'datasets/mouseA/'
  DATAINFO: 'features/mouseA/data_info.json'
  EXCLUDE_BORDER_OBJECTS: True
AUTOENCODER:
  ARCHITECTURE: 'unet_3d'
  TARGET: (64, 64, 64)
  EPOCHS: 5
  BATCH_SIZE: 2
  FEATURES: ['shape', 'texture']
  LATENT_SPACE: 100
  MAX_MEAN: 0.001
  MAX_VAR: 0.001
  MAX_GRADIENT: 1.0
  LOG_INTERVAL: 10
  LARGE_OBJECT_SAMPLES: 5
  MONITOR_PATH: 'models/mouseA/'
PTC:
  ARCHITECTURE: 'ptc++'
  BATCH_SIZE: 1
  EPOCHS: 25
  LATENT_SPACE: 80
  INPUT_DATA: 'datasets/mouseA/pts.h5'
  MONITOR_PATH: 'models/ptc/mouseA/'
  FEATURE_NAME: 'mouseA/ptc_shapef'
  MODEL: 'models/ptc/mouseA/run_2021-09-29/vae_ptc_model_8.pt'
SSL:
  BATCH_SIZE: 16
  K_KNN: 3
  OUTPUT_FOLDER: 'features/mouseA/'
  MONITOR_PATH: 'models/cl/mouseA/'
  USE_PREP_DATASET: 'datasets/mouseA/mito_samples.h5'
  STATE_MODEL: 'models/cl/mouseA/run_2021-10-11/cl_model_3.pt'
  VALIDATION: True
MODE:
  PROCESS: 'clinfer'
CLUSTER:
  ALG: 'kmeans'
  FEAT_LIST: ['sizef', 'distf', 'circf', 'shapef', 'texturef']
  WEIGHTSF: [1, 1, 1, 1, 1]
  N_CLUSTER: 5
  OUTPUTPATH: 'outputs/mouseA/'
  GENERATE_MASKS: True
