SYSTEM:
  NUM_CPUS: 8
  NUM_GPUS: 0
AUTOENCODER:
  ARCHITECTURE: 'unet_3d'
  REGION_LIMIT: None
  CHUNKS_CPU: 4
  UPPER_BOUND: 10000000
  LOWER_BOUND: 0
  TARGET: (64, 64, 64)
  EPOCHS: 5
  BATCH_SIZE: 1
  OUTPUT_FOLDER: 'features/mouseA/'
  FEATURES: ['shape', 'texture']
  LATENT_SPACE: 100
  MAX_MEAN: 0.001
  MAX_VAR: 0.001
  MAX_GRADIENT: 1.0
  LOG_INTERVAL: 10
  PTC_NUM_POINTS: 500
  PTC_SAMPLE_MODE: 'bluenoise'
  BLUE_NOISE_SAMPLE_POINTS: 1000
  LARGE_OBJECT_SAMPLES: 4
DATASET:
  EM_PATH: 'datasets/mouseA/em_export/'
  LABEL_PATH: 'datasets/mouseA/mito_export_unique_id/'
  GT_PATH: 'datasets/mouseA/mito_export_allgroups/'
  FILE_FORMAT: 'png'
  CHUNK_SIZE: [2, 4096, 4096]
  DATAINFO: 'features/mouseA/data_info.json'
  ROOTF: 'features/mouseA/'
MODE:
  PROCESS: ''
  DPRC: 'iter'
CLUSTER:
  ALG: 'kmeans'
  FEAT_LIST: ['surface_to_volumef']
  WEIGHTSF: [1]
  N_CLUSTER: 5
  OUTPUTPATH: 'outputs/mouseA/'
  NEUROGLANCER: False
  GENERATE_MASKS: True
  VISUALIZATION: False
