SYSTEM:
  NUM_CPUS: 8
AUTOENCODER:
  ARCHITECTURE: 'vae_3d'
  REGION_LIMIT: None
  CHUNKS_CPU: 4
  UPPER_BOUND: 100000
  LOWER_BOUND: 100
  TARGET: (128, 128, 128)
  OUPUT_FILE_VOLUMES: 'features/mito.h5'
  DATASET_NAME: 'mito_volumes'

DATASET:
  EM_PATH: 'datasets/human/human_em_export_8nm/'
  LABEL_PATH: 'datasets/human/human_gt_export_8nm/'
  FILE_FORMAT: 'png'
  CHUNK_SIZE: [2, 4096, 4096]
  DATAINFO: 'features/data_info.json'
  SIZEF: 'features/sizef_complete.json'
  DISTF: 'features/distf_complete.json'
