SYSTEM:
  NUM_CPUS: 8
  NUM_GPUS: 0
AUTOENCODER:
  ARCHITECTURE: 'unet_3d'
  REGION_LIMIT: None
  CHUNKS_CPU: 4
  UPPER_BOUND: 100000
  LOWER_BOUND: 100
  TARGET: (128, 128, 128)
  EPOCHS: 5
  BATCH_SIZE: 2
  OUTPUT_FOLDER: 'features/'
  FEATURE: 'texture'
  LATENT_SPACE: 100
  LOG_INTERVAL: 10
DATASET:
  EM_PATH: 'datasets/human/human_em_export_8nm/'
  LABEL_PATH: 'datasets/human/human_gt_export_8nm/'
  FILE_FORMAT: 'png'
  CHUNK_SIZE: [2, 4096, 4096]
  DATAINFO: 'features/data_info.json'
  SIZEF: 'features/sizef_complete.json'
  DISTF: 'features/distf_complete.json'
MODE:
  PROCESS: 'leaveitoutfornow'
  DPRC: 'iter'
CLUSTER:
  ALG: 'affprop'
  FEAT_LIST: ['sizef', 'distf', 'circf']
  WEIGHTSF: [1, 1, 1]
