SYSTEM:
  NUM_CPUS: 8
  NUM_GPUS: 0
AUTOENCODER:
  ARCHITECTURE: 'unet_3d'
  REGION_LIMIT: None
  CHUNKS_CPU: 4
  UPPER_BOUND: 100000
  LOWER_BOUND: 100
  TARGET: (64, 64, 64)
  EPOCHS: 1
  BATCH_SIZE: 1
  OUTPUT_FOLDER: 'features/'
  FEATURES: ['shape', 'texture']
  LATENT_SPACE: 100
  MAX_MEAN: 0.001
  MAX_VAR: 0.001
  MAX_GRADIENT: 1.0
  LOG_INTERVAL: 10
DATASET:
  EM_PATH: 'datasets/human/human_em_export_8nm/'
  LABEL_PATH: 'datasets/human/human_gt_export_8nm/'
  FILE_FORMAT: 'png'
  CHUNK_SIZE: [2, 4096, 4096]
  DATAINFO: 'features/data_info.json'
MODE:
  PROCESS: 'ptctrain'
  DPRC: 'iter'
CLUSTER:
  ALG: 'kmeans'
  FEAT_LIST: ['sizef', 'distf', 'circf', 'shapef', 'texturef']
  WEIGHTSF: [1, 1, 1, 1, 1]
  N_CLUSTER: 3
  OUTPUTPATH: 'outputs/'
