SYSTEM:
  NUM_CPUS: 4
AUTOENCODER:
  ARCHITECTURE: 'vae_3d'
  REGION_LIMIT: 10
  CHUNKS_CPU: 1
  UPPER_BOUND: 100000
  LOWER_BOUND: 100
  TARGET: (128, 128, 128)
  OUPUT_FILE_VOLUMES: 'features/mito.h5'
  DATASET_NAME: 'mito_volumes'

DATASET:
  EM_PATH: 'datasets/r_em/'
  LABEL_PATH: 'datasets/r_gt/'
  FILE_FORMAT: 'png'
